added the first function.
dudugvili/SoftwareEngineering_HW pull request #3
Opened 2023-05-11 11:19 UTC by Tommyl404

can't check further with inputs, need to have function 3 online.
added a flag to the main menu so when case 11 is active it will be false and really terminate the script as it should.

2023-05-11 13:22 UTC, ShirGivon commented
הי, עשיתי את פעולת ההדפסה, הוספתי גם את הפונקציות שאני צריך לעשות על הדרך. 3,4,9

2023-05-14 06:27 UTC, dudugvili commented
@ShirGivon Please remove your changes from this Pull Request and make a new branch of your own with the desired changes

2023-05-14 06:31 UTC, dudugvili commented on Ex1/main.java
> +               case "2":
Unnecessary removal of space

2023-05-14 06:52 UTC, dudugvili commented on Ex1/main.java
> +        /*a do-while loop for taking care of invalid phone numbers, using .next() for only
For proper documentation please refer to this guidelines - 
https://www.oracle.com/il-en/technical-resources/articles/java/javadoc-tool.html

2023-05-14 07:14 UTC, dudugvili requested changes
Please see the comments I've wrote,
also - keep this naming convention:
SomeClass
someFunction
some_variable

2023-05-14 07:16 UTC, dudugvili commented
@Tommyl404 
other than some documentation changes the code looks good.
Fix that and after Shir will remove his changes from here we will merge this PR.

2023-05-14 08:24 UTC, ShirGivon commented
Created new branch function_349. Still need updates, documentation, and Naming conventions.

2023-05-17 07:32 UTC, dudugvili commented on Ex1/Contact.java
> +
Unnecessary

2023-06-21 07:03 UTC, closed without merging