Function fin
dudugvili/SoftwareEngineering_HW pull request #9
Opened 2023-05-16 15:14 UTC by Tommyl404

done with all functions.

2023-05-17 07:52 UTC, dudugvili requested changes

2023-05-17 07:52 UTC, dudugvili commented on Ex1/main.java
> +            while (iterator.hasNext())
```suggestion
            for(Contact con : phone_book)
```
instead of using iterators you can use this simple for loop

2023-05-17 07:52 UTC, dudugvili commented on Ex1/main.java
> +                    return Long.compare(Long.parseLong(b.getPhoneNumber()), Long.parseLong(a.getPhoneNumber()));
You're comparing the phone numbers?
you should compare the names.
Also - please do not use built-in sorting methods and just implement some efficient sort algorithm (quick sort maybe)

2023-05-17 07:52 UTC, dudugvili commented on Ex1/main.java
> +            printContacts(phone_book);
no need to print contacts in this method

2023-05-17 07:52 UTC, dudugvili commented on Ex1/main.java
> +        Scanner sForSave = new Scanner(System.in);
```suggestion
        Scanner s_for_save= new Scanner(System.in);
```

2023-05-17 07:52 UTC, dudugvili commented on Ex1/main.java
> +        String fileName = sForSave.nextLine();
```suggestion
        String file_name= s_for_save.nextLine();
```

2023-05-17 07:52 UTC, dudugvili commented on Ex1/main.java
> +                Contact tmpContact = iterator.next();
```suggestion
                Contact tmp_contact= iterator.next();
```

2023-05-17 07:52 UTC, dudugvili commented on Ex1/main.java
> +            ArrayList<Contact> uniqueContacts = new ArrayList<>();
```suggestion
            ArrayList<Contact> unique_contacts = new ArrayList<>();
```

2023-05-18 13:30 UTC, Tommyl404 commented on Ex1/main.java
> +                    return Long.compare(Long.parseLong(b.getPhoneNumber()), Long.parseLong(a.getPhoneNumber()));
Function 6 explicitly needs to compare phone numbers from what we were told to do:
 מיון ספר הטלפונים ע"י טלפון )נומרי( מהגדול לקטן ביעילות
 If it's numerical from small to big then this is ok from what I understand.

2023-05-18 13:32 UTC, Tommyl404 commented on Ex1/main.java
> +            while (iterator.hasNext())
This is Shir's function.

2023-05-18 13:32 UTC, Tommyl404 commented on Ex1/main.java
> +        Scanner sForSave = new Scanner(System.in);
This is Shir's function.

2023-05-18 13:33 UTC, Tommyl404 commented on Ex1/main.java
> +        String fileName = sForSave.nextLine();
This is Shir's function.

2023-05-18 13:33 UTC, Tommyl404 commented on Ex1/main.java
> +                Contact tmpContact = iterator.next();
This is Shir's function.

2023-06-21 07:03 UTC, closed without merging